[package]
name = "wasm-rust"
version = "0.1.0"
authors = ["Fabian Schnider <fabian@meisterlabs.com>"]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.50"
